export enum EErrorMessage {
  UNAUTHORISED_ERROR = '90',
  FORBIDDEN_ERROR = '100',
  SESSION_EXPIRED_CODE = '101',
  DUPLICATE_EMAIL_ADDRESS = '102',
  EMAIL_PASSWORD_MISMATCH = '103',
  USER_WITH_THIS_EMAIL_NOT_FOUND = '104',
  COULD_NOT_ADD_MEDIA = '105',
  COULD_NOT_DELETE_MEDIA = '106',
  INTERNAL_SERVER_ERROR = '500',
  FB_AUTH_CODE_EXPIRED_ERROR = '1000',
  FB_RIDERECT_URI_ERROR = '1001',
  FB_OAUTH_ERROR = '1002',
  FB_PAGE_ERROR = '1003',
  FB_EMPTY_POST_ERROR = '1004',
  FB_DUPLICATE_MESSAGE_ERROR = '1005',
  FB_MEDIA_TOO_LARGE = '1006',
  FB_MEDIA_MISSING = '1007',
  FB_TOO_MANY_REQUESTS = '1008',
  ADD_POST_ERROR = '10',
  TW_AUTHENTICATE_ERROR = '32',
  TW_INVALID_MEDIA_ERROR = '324',
  CONNECTION_DELETE_ERROR = '10000',
}

export const ErrorMessageMap = new Map([
  [EErrorMessage.ADD_POST_ERROR, 'Could not add post. Please try again.'],
  [EErrorMessage.CONNECTION_DELETE_ERROR, 'Could not delete connection. Please try again'],
  [EErrorMessage.COULD_NOT_ADD_MEDIA, 'Could not add media. Please try again.'],
  [EErrorMessage.COULD_NOT_DELETE_MEDIA, 'Could not delete media. Please try again.'],
  [EErrorMessage.DUPLICATE_EMAIL_ADDRESS, 'This user has already an Buffer account.'],
  [EErrorMessage.EMAIL_PASSWORD_MISMATCH, "Email address or password doesn't match."],
  [EErrorMessage.FB_AUTH_CODE_EXPIRED_ERROR, 'Authorization code has expired.'],
  [EErrorMessage.FB_DUPLICATE_MESSAGE_ERROR, "Whoops, it looks like you've posted that one recently. Please try posting others."],
  [EErrorMessage.FB_EMPTY_POST_ERROR, 'The post is empty. Please enter a message to share.'],
  [EErrorMessage.FB_MEDIA_MISSING, 'Media file is missing. Please try again.'],
  [EErrorMessage.FB_MEDIA_TOO_LARGE, 'Media file is too large. Please try again.'],
  [EErrorMessage.FB_OAUTH_ERROR, 'Could not log into Facebook. Please try again.'],
  [EErrorMessage.FB_PAGE_ERROR, 'Could not get Facebook Pages. Please try again.'],
  [EErrorMessage.FB_RIDERECT_URI_ERROR, 'Riderct URL is missing. Please try again.'],
  [EErrorMessage.FB_TOO_MANY_REQUESTS, 'Too many requests. Please try again.'],
  [EErrorMessage.FORBIDDEN_ERROR, 'Request not allowed. Please try again.'],
  [EErrorMessage.INTERNAL_SERVER_ERROR, 'Something bad happened. Please try again.'],
  [EErrorMessage.SESSION_EXPIRED_CODE, 'Session has expired. Please login again.'],
  [EErrorMessage.UNAUTHORISED_ERROR, 'Authorization failed. Please login again.'],
  [EErrorMessage.USER_WITH_THIS_EMAIL_NOT_FOUND, 'A user with this email is not found.'],
  [EErrorMessage.TW_AUTHENTICATE_ERROR, 'Could not authenticate. Please try again.'],
  [EErrorMessage.TW_INVALID_MEDIA_ERROR, 'Media file is missing. Please try again.']
]);
