export enum ENetworkVisibility {
  CONNECTIONS = 'CONNECTIONS',
  LOGGED_IN = 'LOGGED_IN',
  PUBLIC = 'PUBLIC',
}

export enum ELifeCycleState {
  DELETED = 'DELETED',
  DRAFT = 'DRAFT',
  PROCESSING = 'PROCESSING',
  PROCESSING_FAILED = 'PROCESSING_FAILED',
  PUBLISHED = 'PUBLISHED',
  PUBLISHED_EDITED = 'PUBLISHED_EDITED',
}

export enum EShareMediaCategory {
  ANSWER = 'ANSWER',
  ARTICLE = 'ARTICLE',
  CAROUSEL = 'CAROUSEL',
  IMAGE = 'IMAGE',
  JOB = 'JOB',
  LEARNING_COURSE = 'LEARNING_COURSE',
  LIVE_VIDEO = 'LIVE_VIDEO',
  NATIVE_DOCUMENT = 'NATIVE_DOCUMENT',
  NONE = 'NONE',
  QUESTION = 'QUESTION',
  RICH = 'RICH',
  TOPIC = 'TOPIC',
  URN_REFERENCE = 'URN_REFERENCE',
  VIDEO = 'VIDEO',
}

export enum EMediaStatus {
  FAILED = 'FAILED',
  PROCESSING = 'PROCESSING',
  READY = 'READY',
}
